name: Deploy ERP System

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /home/ubuntu/wholesale-erp

            git reset --hard
            git pull origin main

            sudo pkill -f uvicorn || true

            nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > output.log 2>&1 &
